#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
apt-get -y update
apt-get -y install nginx

echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

service nginx reload
