#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo echo "server {
    listen 80;
    server_name _;

    return 301 http://100.26.11.71/redirect_me/;
}"  | sudo tee /etc/nginx/sites-available/default1

sudo cat /etc/nginx/sites-available/default | sudo tee -a /etc/nginx/sites-available/default1
sudo mv /etc/nginx/sites-available/default1 /etc/nginx/sites-available/default


sudo service nginx reload
