#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y install nginx

touch /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html/index.nginx-debian.html;
    
    location /redirect_me {
        return 301 http://100.26.11.71/redirect_me/;
        }
    error_page 404 /404.html;
    location /404 {
    root /var/www/html;
    internal;
    }
}"  | sudo tee /etc/nginx/sites-available/default


sudo service nginx reload
