#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
apt-get -y update
apt-get -y install nginx

mkdir -p /var/www/html
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

echo "server {
	listen 80;
	listen [::]:80;

	add_header X-Served-By $(hostname);
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;	

	location /redirect_me{
		return 301 http://salimjj03.tech/;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" | tee /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html

service nginx restart
