#!/usr/bin/env bash
# listening on port 80 of all the server’s active IPv4 IPs
apt -y update
apt -y install nginx

echo "server {
	listen 0.0.0.0:80;
	listen [::]:80;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html

	server_name _;
	
	location / {
		try \$uri \$uri/ =404;
	}
}" | tee /var/www/html/default

service nginx restart
