#!/usr/bin/env bash
# This script test your luck
num=1
while [ $num -le 100 ]
do
	if [ $((num % 5)) -eq  0 ] && [ $((num % 3)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((num % 5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((num % 3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo "$num"
	fi
	(( num++ ))
done
