#!/usr/bin/env bash
# This sicript edit host file
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sed '/127.0.0.2/ a 8.8.8.8       facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
